<?php

namespace Database\Seeders;

use App\Models\Classroom;
use App\Models\User;
use Illuminate\Database\Seeder;

class ClassroomSeeder extends Seeder
{
    public function run(): void
    {
        $teachers = User::role('teacher')->get();
        $students = User::role('student')->get();

        $classroomData = [
            // Teacher 1
            [
                'name'    => 'Class 10-A Computer Science',
                'subject' => 'Computer Science',
            ],
            [
                'name'    => 'Class 9-B Information Technology',
                'subject' => 'Information Technology',
            ],
            // Teacher 2
            [
                'name'    => 'Class 11-A Mathematics',
                'subject' => 'Mathematics',
            ],
            [
                'name'    => 'Class 10-C Mathematics',
                'subject' => 'Mathematics',
            ],
            // Teacher 3
            [
                'name'    => 'Class 9-A Science',
                'subject' => 'Science',
            ],
            [
                'name'    => 'Class 11-B Physics',
                'subject' => 'Physics',
            ],
        ];

        foreach ($classroomData as $index => $data) {
            // Assign 2 classrooms per teacher
            $teacher = $teachers[$index < 2 ? 0 : ($index < 4 ? 1 : 2)];

            $classroom = Classroom::create([
                'teacher_id' => $teacher->id,
                'name'       => $data['name'],
                'subject'    => $data['subject'],
                'is_active'  => true,
                // join_code is auto-generated by the model's booted() method
            ]);

            // Enroll 8–10 random students in each classroom
            $enrolled = $students->random(rand(8, 10));

            foreach ($enrolled as $student) {
                $classroom->students()->syncWithoutDetaching([
                    $student->id => ['joined_at' => now()],
                ]);
            }
        }

        $this->command->info('Classrooms created: 6 total, students enrolled');
    }
}