<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>Session Report</title>
    <style>
        body { font-family: Arial, sans-serif; font-size: 12px; color: #111; margin: 0; padding: 0; }
        h1 { font-size: 20px; margin-bottom: 4px; }
        h2 { font-size: 14px; border-bottom: 1px solid #e5e7eb; padding-bottom: 4px; margin-top: 20px; }
        table { width: 100%; border-collapse: collapse; margin-top: 8px; }
        th { background: #f3f4f6; text-align: left; padding: 6px 8px; font-size: 11px; border: 1px solid #e5e7eb; }
        td { padding: 6px 8px; font-size: 11px; border: 1px solid #e5e7eb; }
        .badge { display: inline-block; padding: 2px 6px; border-radius: 3px; font-size: 10px; }
        .stat-label { color: #6b7280; font-size: 10px; text-transform: uppercase; }
        .stat-value { font-size: 18px; font-weight: bold; color: #111; }
        .text-right { text-align: right; }
        .text-center { text-align: center; }
        .footer { position: fixed; bottom: -30px; left: 0px; right: 0px; height: 30px; font-size: 10px; color: #6b7280; text-align: center; border-top: 1px solid #e5e7eb; padding-top: 8px; }
        .page-number:after { content: counter(page); }
        .bg-warning { background-color: #fffbeb; }
    </style>
</head>
<body>
    <div class="footer">
        Generated by BYOD Classroom System • Page <span class="page-number"></span>
    </div>

    <h1>BYOD Classroom Management System</h1>
    <p style="margin: 0; color: #6b7280;">Session Report • Generated {{ now()->format('Y-m-d H:i:s') }}</p>
    <hr style="border: 0; border-top: 1px solid #e5e7eb; margin: 15px 0;">

    <table>
        <tr>
            <td style="border: none; padding: 0; vertical-align: top;">
                <strong>Session:</strong> {{ $session->title }}<br>
                <strong>Classroom:</strong> {{ $session->classroom->name }} ({{ $session->classroom->subject }})<br>
                <strong>Teacher:</strong> {{ $session->classroom->teacher->name }}
            </td>
            <td style="border: none; padding: 0; vertical-align: top; text-align: right;">
                <strong>Status:</strong> {{ ucfirst($session->status) }}<br>
                <strong>Started:</strong> {{ $session->started_at?->format('Y-m-d H:i') }}<br>
                <strong>Ended:</strong> {{ $session->ended_at?->format('Y-m-d H:i') ?? '—' }}
            </td>
        </tr>
    </table>

    <h2>Summary Statistics</h2>
    <table>
        <tr>
            <td style="text-align: center;">
                <div class="stat-label">Total Students</div>
                <div class="stat-value">{{ $totalStudents }}</div>
            </td>
            <td style="text-align: center;">
                <div class="stat-label">Total Violations</div>
                <div class="stat-value">{{ $totalViolations }}</div>
            </td>
            <td style="text-align: center;">
                <div class="stat-label">Resources Shared</div>
                <div class="stat-value">{{ $resourcesShared }}</div>
            </td>
            <td style="text-align: center;">
                <div class="stat-label">Duration</div>
                <div class="stat-value">{{ $duration ?? '—' }}</div>
            </td>
        </tr>
    </table>

    <h2>Student Breakdown</h2>
    <table>
        <thead>
            <tr>
                <th>Student Name</th>
                <th>Device</th>
                <th>Joined At</th>
                <th>Violations</th>
                <th>Warning Level</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($sessionDevices as $sd)
                <tr class="{{ $sd->violation_count >= 2 ? 'bg-warning' : '' }}">
                    <td>{{ $sd->device->user->name }}</td>
                    <td>{{ $sd->device->name }}</td>
                    <td>{{ $sd->joined_at?->format('H:i:s') ?? '—' }}</td>
                    <td>{{ $sd->violation_count }}</td>
                    <td>{{ $sd->warningLevel() }}/3</td>
                </tr>
            @endforeach
            @if ($sessionDevices->isEmpty())
                <tr>
                    <td colspan="5" style="text-align: center; color: #6b7280;">No students joined this session.</td>
                </tr>
            @endif
        </tbody>
    </table>

    @if ($totalViolations > 0)
        <h2>Violation Breakdown</h2>
        <table style="width: 50%;">
            <thead>
                <tr>
                    <th>Type</th>
                    <th>Count</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>Tab Switch</td>
                    <td>{{ $violationBreakdown['tab_switch'] ?? 0 }}</td>
                </tr>
                <tr>
                    <td>Window Blur</td>
                    <td>{{ $violationBreakdown['window_blur'] ?? 0 }}</td>
                </tr>
                <tr>
                    <td>Fullscreen Exit</td>
                    <td>{{ $violationBreakdown['fullscreen_exit'] ?? 0 }}</td>
                </tr>
            </tbody>
        </table>
    @endif

    <h2>Shared Resources</h2>
    <table>
        <thead>
            <tr>
                <th>Title</th>
                <th>Type</th>
                <th>Shared At</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($session->resources as $resource)
                <tr>
                    <td>{{ $resource->title }}</td>
                    <td>{{ ucfirst($resource->type) }}</td>
                    <td>{{ $resource->created_at->format('Y-m-d H:i:s') }}</td>
                </tr>
            @endforeach
            @if ($session->resources->isEmpty())
                <tr>
                    <td colspan="3" style="text-align: center; color: #6b7280;">No resources shared.</td>
                </tr>
            @endif
        </tbody>
    </table>

    <h2>Activity Timeline</h2>
    <table>
        <thead>
            <tr>
                <th>Time</th>
                <th>Action</th>
                <th>Description</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($session->activityLogs as $log)
                <tr>
                    <td style="white-space: nowrap;">{{ $log->created_at->format('Y-m-d H:i:s') }}</td>
                    <td style="font-family: monospace;">{{ $log->action }}</td>
                    <td>{{ $log->description }}</td>
                </tr>
            @endforeach
            @if ($session->activityLogs->isEmpty())
                <tr>
                    <td colspan="3" style="text-align: center; color: #6b7280;">No activity logged.</td>
                </tr>
            @endif
        </tbody>
    </table>
</body>
</html>
