<?php

namespace App\Livewire\Teacher;

use App\Models\ActivityLog;
use App\Models\Classroom;
use Livewire\Component;
use Illuminate\Support\Facades\Auth;

class ClassroomCreate extends Component
{
    public string $name    = '';
    public string $subject = '';

    public function rules(): array
    {
        return [
            'name'    => 'required|string|min:3|max:100',
            'subject' => 'required|string|min:2|max:60',
        ];
    }

    public function create(): void
    {
        $this->validate();

        $classroom = Classroom::create([
            'teacher_id' => Auth::id(),
            'name'       => $this->name,
            'subject'    => $this->subject,
            'is_active'  => true,
            // join_code auto-generated by model booted()
        ]);

        ActivityLog::record(
            action: 'classroom.created',
            description: "Classroom created: {$classroom->name}",
        );

        session()->flash('success', 'Classroom created successfully.');

        $this->redirectRoute('teacher.classrooms.show', $classroom);
    }

    public function render()
    {
        return view('livewire.teacher.classroom-create');
    }
}